version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pragya_sh
      POSTGRES_PASSWORD: pragya_zopsmart
      POSTGRES_DB: test_db
