version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
